blog/blog/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^blog/',include('myblog.urls',namespace='myblog')),
    url(r'^comment/',include('comment.urls',namespace='comment'))
]

blog/comment/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'article/(?P<article_pk>\d+)/$',views.article_comment,name='article_comment')
]

blog/myblog/urls.py
from django.conf.urls import url
from . import views


urlpatterns=[
    url(r'^$',views.index,name='index'),
    url(r'^article/(?P<pk>\d+)/$',views.detail,name='detail'),
    url(r'^guilei/(?P<year>[0-9]{4})/(?P<month>[0-9]{2})/$',views.guidang,name='guidang'),
    url(r'^category/(?P<pk>\d+)/$',views.category,name='category'),
]

blog/comment/models.py
from __future__ import unicode_literals

from django.db import models
from django.utils.six import python_2_unicode_compatible


@python_2_unicode_compatible
class Mycomment(models.Model):
    name = models.CharField(max_length=100)
    email = models.CharField(max_length=200)
    url = models.URLField(blank=True)
    text = models.TextField()
    create_time = models.DateTimeField(auto_now_add=True)
    article = models.ForeignKey('myblog.Article')

    def __str__(self):
        return self.text[:20]

blog/myblog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.six import python_2_unicode_compatible
from django.core.urlresolvers import reverse

@python_2_unicode_compatible
class Category(models.Model):
    cname = models.CharField(max_length=40)
    isDelete = models.BooleanField(default=False)
    def __str__(self):
        return self.cname



@python_2_unicode_compatible
class Tag(models.Model):
    tname = models.CharField(max_length=100)
    isDelete = models.BooleanField(default=False)
    def __str__(self):
        return self.tname


@python_2_unicode_compatible
class Article(models.Model):
    atitle = models.CharField(max_length=40)
    abody = models.TextField()
    create_time = models.DateTimeField()
    modify_time = models.DateTimeField()
    zhaiyao = models.CharField(max_length=150,blank=True)
    category = models.ForeignKey(Category)
    tag = models.ManyToManyField(Tag,blank=True)
    user = models.ForeignKey(User)
    def __str__(self):
        return self.atitle

    def get_url(self):
        return reverse('myblog:detail',kwargs={'pk':self.pk})

blog/comment/forms.py
from django import forms
from .models import Mycomment

class CommentForm(forms.ModelForm):
    class Meta:
        model = Mycomment
        fields = ['name', 'email', 'url', 'text']

blog/comment/views.py
from django.shortcuts import render,redirect,get_object_or_404
from myblog.models import Article
from .models import Mycomment
from .forms import CommentForm


def article_comment(request,article_pk):
    article = get_object_or_404(Article,pk=article_pk)
    if request.method == 'POST':
        form = CommentForm(request.Form)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.article = article
            comment.save()
            return redirect(article)
        else:

            comment_list = post.comment_set.all()
            context = {'article': article,
                       'form': form,
                       'comment_list': comment_list
                       }
            return render(request, 'blog/detail.html', context=context)
        return redirect(article)

blog/myblog/views.py
from django.shortcuts import render,get_object_or_404
from models import *
from comment.forms import CommentForm

def index(request):
    article_list = Article.objects.all().order_by('create_time')
    context = {'article_list':article_list,}
    return render(request,'blog/index.html',context)

def detail(request,pk):
    article = get_object_or_404(Article,pk=pk)
    form = CommentForm()
    comment_list = article.mycomment_set.all()
    context = {'article':article,'form':form,'comment_list':comment_list}
    return render(request,'blog/detail.html',context)

def guidang(request,year,month):
    article_list = Article.objects.filter(create_time__year=year,create_time__month=month).order_by("-create_time")
    context = {'article_list':article_list}
    return render(request,'blog/index.html',context)

def category(request,pk):
    cate = get_object_or_404(Category,pk=pk)
    article_list = Article.objects.filter(category=cate).order_by('-create_time')
    context = {'article_list':article_list}
    return render(request,'blog/index.html',context)

blog/templates/base.html
{% load staticfiles %}
{% load blog_tag %}

<!DOCTYPE html>

<html>
<head>
    <title>Black &amp; White</title>

    <!-- meta -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- css -->
    <link rel="stylesheet" href="{% static 'myblog/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <link rel="stylesheet" href="{% static 'myblog/css/pace.css' %}">
    <link rel="stylesheet" href="{% static 'myblog/css/custom.css' %}">

    <!-- js -->
    <script src="{% static 'myblog/js/jquery-2.1.3.min.js' %}"></script>
    <script src="{% static 'myblog/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'myblog/js/pace.min.js' %}"></script>
    <script src="{% static 'myblog/js/modernizr.custom.js' %}"></script>
</head>
<div class="copyrights">Collect from <a href="http://www.cssmoban.com/">网页模板</a></div>
<div class="copyrights">Modified by <a href="http://zmrenwu.com/">追梦人物的博客</a></div>


<div class="container">
    <header id="site-header">
        <div class="row">
            <div class="col-md-4 col-sm-5 col-xs-8">
                <div class="logo">
                    <h1><a href="index.html"><b>Black</b> &amp; White</a></h1>
                </div>
            </div><!-- col-md-4 -->
            <div class="col-md-8 col-sm-7 col-xs-4">
                <nav class="main-nav" role="navigation">
                    <div class="navbar-header">
                        <button type="button" id="trigger-overlay" class="navbar-toggle">
                            <span class="ion-navicon"></span>
                        </button>
                    </div>

                    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                        <ul class="nav navbar-nav navbar-right">
                            <li class="cl-effect-11"><a href="index.html" data-hover="首页">首页</a></li>
                            <li class="cl-effect-11"><a href="full-width.html" data-hover="博客">博客</a></li>
                            <li class="cl-effect-11"><a href="about.html" data-hover="关于">关于</a></li>
                            <li class="cl-effect-11"><a href="contact.html" data-hover="联系">联系</a></li>
                        </ul>
                    </div><!-- /.navbar-collapse -->
                </nav>
                <div id="header-search-box">
                    <a id="search-menu" href="#"><span id="search-icon" class="ion-ios-search-strong"></span></a>
                    <div id="search-form" class="search-form">
                        <form role="search" method="get" id="searchform" action="#">
                            <input type="search" placeholder="搜索" required>
                            <button type="submit"><span class="ion-ios-search-strong"></span></button>
                        </form>
                    </div>
                </div>
            </div><!-- col-md-8 -->
        </div>
    </header>
</div>
<div class="content-body">
    <div class="container">
        <div class="row">
            <main class="col-md-8">
                {% block main %}
                {% endblock main %}

            </main>
        <aside class="col-md-4">
            {% block toc %}
            {% endblock toc %}
        </aside>
                </div>
    </div>
</div>
<footer id="site-footer">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <p class="copyright">&copy 2017 - 采集自<a href="http://www.cssmoban.com/"
                                                        target="_blank" title="模板之家">模板之家</a>
                    - 由<a href="http://zmrenwu.com/" title="网页模板" target="_blank">追梦人物的博客</a>修改
                </p>
            </div>
        </div>
    </div>
</footer>

<!-- Mobile Menu -->
<div class="overlay overlay-hugeinc">
    <button type="button" class="overlay-close"><span class="ion-ios-close-empty"></span></button>
    <nav>
        <ul>
            <li><a href="index.html">首页</a></li>
            <li><a href="full-width.html">博客</a></li>
            <li><a href="about.html">关于</a></li>
            <li><a href="contact.html">联系</a></li>
        </ul>
    </nav>
</div>

<script src="{% static 'myblog/js/script.js' %}"></script>

</body>
</html>

blog/templates/blog/detail.html
{% extends 'base.html' %}



                    {% block main %}
                    <article class="post post-{{ article.pk }}">
                    <header class="entry-header">
                        <h1 class="entry-title">{{ article.atitle }}</h1>
                        <div class="entry-meta">
                            <span class="post-category"><a href="#">{{ article.category.cname }}</a></span>
                            <span class="post-date"><a href="#"><time class="entry-date"
                                                                      datetime="{{ article.create_time }}">{{ article.create_time }}</time></a></span>
                            <span class="post-author"><a href="#">{{ article.author }}</a></span>
                            <span class="comments-link"><a href="#">4 评论</a></span>
                            <span class="views-count"><a href="#">588 阅读</a></span>
                        </div>
                    </header>
                    <div class="entry-content clearfix">
                    {{ article.abody }}
                    </div>
                </article>
                <section class="comment-area" id="comment-area">
                    <hr>
                    <h3>发表评论</h3>
                    <form action="{% url 'comment:article_comment' article_pk %}" method="post" class="comment-form">
                        {% csrf_token %}
                        <div class="row">
                            <div class="col-md-4">
                                <label for="{{ form.name.id_for_label }}">名字：</label>
                                {{ form.name }}
                                {{ form.name.errors }}
                            </div>
                            <div class="col-md-4">
                                <label for="{{ form.email.id_for_label }}">邮箱：</label>
                                {{ form.email }}
                                {{ form.email.errors }}
                            </div>
                            <div class="col-md-4">
                                <label for="{{ form.url.id_for_label }}">网址：</label>
                                {{ form.url }}
                                {{ form.url.errors }}
                            </div>
                            <div class="col-md-12">
                                <label for="{{ form.text.id_for_label }}">评论：</label>
                                {{ form.text }}
                                {{ form.text.errors }}
                                 <button type="submit" class="comment-btn">发表</button>
                            </div>
                        </div>    <!-- row -->
                    </form>
                    <div class="comment-list-panel">
                        {% for comment in comment_list }
                        <ul class="comment-list list-unstyled">
                            <li class="comment-item">
                                <span class="nickname">{{ comment.name }}</span>
                                <time class="submit-date" datetime="{{ comment.create_time }}">{{ comment.create_time }}</time>
                                <div class="text">
                                    {{ comment.text }}
                                </div>
                            </li>
                            {% empty %}
                            暂无评论
                        {% endfor %}
                        </ul>
                    </div>
                </section>
            {% endblock main %}
            {% block toc %}
                <div class="widget widget-content">
                    <h3 class="widget-title">文章目录</h3>
                    <ul>
                        <li>
                            <a href="#">教程特点</a>
                        </li>
                        <li>
                            <a href="#">谁适合这个教程</a>
                        </li>
                        <li>
                            <a href="#">在线预览</a>
                        </li>
                        <li>
                            <a href="#">资源列表</a>
                        </li>
                        <li>
                            <a href="#">获取帮助</a>
                        </li>
                    </ul>
                </div>
                <div class="widget widget-recent-posts">
                    <h3 class="widget-title">最新文章</h3>
                    <ul>
                        <li>
                            <a href="#">Django 博客开发入门教程：前言</a>
                        </li>
                        <li>
                            <a href="#">Django 博客使用 Markdown 自动生成文章目录</a>
                        </li>
                        <li>
                            <a href="#">部署 Django 博客</a>
                        </li>
                    </ul>
                </div>
                <div class="widget widget-archives">
                    <h3 class="widget-title">归档</h3>
                    <ul>
                        <li>
                            <a href="#">2017 年 5 月</a>
                        </li>
                        <li>
                            <a href="#">2017 年 4 月</a>
                        </li>
                        <li>
                            <a href="#">2017 年 3 月</a>
                        </li>
                    </ul>
                </div>

                <div class="widget widget-category">
                    <h3 class="widget-title">分类</h3>
                    <ul>
                        <li>
                            <a href="#">Django 博客教程 <span class="post-count">(13)</span></a>
                        </li>
                        <li>
                            <a href="#">Python 教程 <span class="post-count">(11)</span></a>
                        </li>
                        <li>
                            <a href="#">Django 用户认证 <span class="post-count">(8)</span></a>
                        </li>
                    </ul>
                </div>

                <div class="widget widget-tag-cloud">
                    <h3 class="widget-title">标签云</h3>
                    <ul>
                        <li>
                            <a href="#">Django</a>
                        </li>
                        <li>
                            <a href="#">Python</a>
                        </li>
                        <li>
                            <a href="#">Java</a>
                        </li>
                        <li>
                            <a href="#">笔记</a>
                        </li>
                        <li>
                            <a href="#">文档</a>
                        </li>
                        <li>
                            <a href="#">AngularJS</a>
                        </li>
                        <li>
                            <a href="#">CSS</a>
                        </li>
                        <li>
                            <a href="#">JavaScript</a>
                        </li>
                        <li>
                            <a href="#">Snippet</a>
                        </li>
                        <li>
                            <a href="#">jQuery</a>
                        </li>
                    </ul>
                </div>
                <div class="rss">
                    <a href=""><span class="ion-social-rss-outline"></span> RSS 订阅</a>
                </div>
            {% endblock toc %}

blog/templates/blog/index.html
{% extends 'base.html' %}


{% block main %}
    {% get_new_article as atrticle_list %}
                {% for x in article_list %}
                <article class="post post-{{ x.pk }}">
                    <header class="entry-header">
                        <h1 class="entry-title">
                            <a href="{{ article.get_url }}">{{ x.atitle }}</a>
                        </h1>
                        <div class="entry-meta">
                            <span class="post-category"><a href="#">{{ x.category.cname }}</a></span>
                            <span class="post-date"><a href="#"><time class="entry-date"
                                                                      datetime="{{ x.create_time }}">{{ x.create.time }}</time></a></span>
                            <span class="post-author"><a href="#">{{ x.uesr }}</a></span>
                            <span class="comments-link"><a href="#">4 评论</a></span>
                            <span class="views-count"><a href="#">588 阅读</a></span>
                        </div>
                    </header>
                    <div class="entry-content clearfix">
                        <p>{{ x.zhaiyao }}</p>
                        <div class="read-more cl-effect-14">
                            <a href="{{ article.get_url }}" class="more-link">继续阅读 <span class="meta-nav">→</span></a>
                        </div>
                    </div>
                </article>
                {% empty %}
                    <div class="no-post">暂时还没有发布的文章！</div>
                {% endfor %}

                <!-- 简单分页效果
                <div class="pagination-simple">
                    <a href="#">上一页</a>
                    <span class="current">第 6 页 / 共 11 页</span>
                    <a href="#">下一页</a>
                </div>
                -->
                <div class="pagination">
                    <ul>
                        <li><a href="">1</a></li>
                        <li><a href="">...</a></li>
                        <li><a href="">4</a></li>
                        <li><a href="">5</a></li>
                        <li class="current"><a href="">6</a></li>
                        <li><a href="">7</a></li>
                        <li><a href="">8</a></li>
                        <li><a href="">...</a></li>
                        <li><a href="">11</a></li>
                    </ul>
                </div>
{% endblock main %}



                {% block toc %}
                <div class="widget widget-recent-posts">
                    <h3 class="widget-title">最新文章</h3>
                    <ul>
                        <li>
                            <a href="#">Django 博客开发入门教程：前言</a>
                        </li>
                        <li>
                            <a href="#">Django 博客使用 Markdown 自动生成文章目录</a>
                        </li>
                        <li>
                            <a href="#">部署 Django 博客</a>
                        </li>
                    </ul>
                </div>
                {% new-date as date_list %}
                <div class="widget widget-archives">
                    <h3 class="widget-title">归档</h3>
                    <ul>
                        {% for date in date_list %}
                        <li>
                            <a href="{% url 'blog:guidang' date.year date.month %}">{{ date.year }}年{{ date.month }}月</a>
                        </li>
                        {% empty %}
                        <h6>暂无归档！</h6>
                        {% endfor %}

                    </ul>
                </div>

                <div class="widget widget-category">
                    <h3 class="widget-title">分类</h3>
                    {% new_category as my_category %}
                    <ul>
                        {% for category in my_category %}
                        <li>
                            <a href="{% url 'blog:category' category.pk %}">{{ category.cname }} <span class="post-count">(13)</span></a>
                        </li>
                        {% empty %}
                        <h7>暂无分类！</h7>
                        {% endfor %}

                    </ul>
                </div>

                <div class="widget widget-tag-cloud">
                    <h3 class="widget-title">标签云</h3>
                    {% new_tag as tag_list %}
                    <ul>
                        {% for tag in tag_list %}
                        <li>
                            <a href="#">{{ tag.tname }}</a>
                        </li>
                        {% empty %}
                            <h7>没有标签</h7>
                        {% endfor %}


                    </ul>
                </div>
                <div class="rss">
                    <a href=""><span class="ion-social-rss-outline"></span> RSS 订阅</a>
                </div>
                {% endblock toc %}